### ISSUE TITLE
A little confused about the config.

### ISSUE THREAD

**Issue by tr3vr** [zazuko/tbbt-ld#1]
Hi, just came across trifid-ld and hoping to get it to work, but as of now I'm only getting a 404 error page, I'm running it using docker on a Google Compute Engine VM instance, the server starts but when I navigate to the URI that is the subject in the RDF graph, I don't see the output in trifid-ld, any help would be great.

Thanks,
Trevor.

**Comment by ktk** [comment]
Hi Trevor,

The configuration is still a bit confusing indeed, we have some discussions right now about how to simplify this. Did you try with the default configuration and the sample dataset or did you start changing it? As I pointed you to this I suppose you want to use it for a SPARQL endpoint, right?

**Comment by tr3vr** [comment]
I did try with the default config. I cloned the tbbt-ld repo and moved the /persons and /dist folders into the trifid-ld working directories, but didn't manage to get it to work, I'd like to use my Fuseki2 endpoint that is on another server, I replaced localhost with that servers IP, within my sample dataset,  I changed the URI's to match trifid-ld's IP.. What would be really helpful would be to put up a sample config.sparql.js with external endpoint IPs and trifid-ld IPs along with a little bit of commenting ( even if the IPs are pseudo.) Thanks again Adrian.. really looking forward to getting this to work today! If it doesn't Im going to have to start working setting up Pubby :/

**Comment by ktk** [comment]
Sorry we are in different timezones I guess. I will paste my config in a gist bit later today.

**Comment by tr3vr** [comment]
Thanks Adrian.. really appreciate it

**Comment by ktk** [comment]
There we go: https://gist.github.com/ktk/96e8966b4109e37c09f3

if you have questions we might move the discussion to Gitter, I tried creating a room, you might check if you can join that with your Github account: https://gitter.im/zazukoians/trifid-ld?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by ktk** [comment]
I close this as we continue discussion on Gitter.
