### ISSUE TITLE
add rdfjs serialized (JS code) quads for direct import

### ISSUE THREAD

**Issue by bergos** [zazuko/tbbt-ld#3]
A serializer that generates JS code which creates the term+ quads + dataset could be used to generate a dist of the triples/quads and would allow to require the data without the need to handle the dist files with a parser.

**Comment by tpluscode** [comment]
do you have the time to do this one? might need the example dataset imported for the examples on zazuko.com

if you don't have the bandwidth right now let me send a PR with exports of dataset factory methods
